// AUTO-GENERATED from the existing question_bank_DRAFT.csv (definition
// questions). Enriched with moduleTag/topicTag/difficulty/testForm/
// isActive; `explanation` reuses the correct option's own text, since
// each option in this pool is itself a full definition.
import type { QuizQuestionSeed } from "./quizQuestionTypes";

export const DEFINITION_QUESTIONS: QuizQuestionSeed[] = [
  {
    questionId: 'def-1',
    question: 'Which of the following best describes "phishing"?',
    optionA: 'Phishing is a social-engineering attack where an attacker sends fraudulent messages (usually email) that impersonate a trusted sender to trick the recipient into revealing credentials, clicking a malicious link, or downloading malware. It relies on deception rather than technical exploitation.',
    optionB: 'The CIA Triad is the foundational model of information security: Confidentiality (only authorized parties can access data), Integrity (data cannot be altered undetected), and Availability (systems and data are accessible when needed). Most security controls map to protecting one or more of these three properties.',
    optionC: 'A zero-day is a software vulnerability that is unknown to the vendor (and therefore has no patch yet) at the time it is discovered or exploited. Zero-day exploits are especially dangerous because standard signature-based defenses have nothing to detect. Mitigated with defense-in-depth, network segmentation, and behavior-based detection rather than relying on patches alone.',
    optionD: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    correctOption: 'A',
    topic: 'phishing',
    moduleTag: 'Social Engineering',
    topicTag: 'Phishing',
    difficulty: 'Easy',
    testForm: 'PRE_A',
    explanation: 'Phishing is a social-engineering attack where an attacker sends fraudulent messages (usually email) that impersonate a trusted sender to trick the recipient into revealing credentials, clicking a malicious link, or downloading malware. It relies on deception rather than technical exploitation.',
    isActive: true,
  },
  {
    questionId: 'def-2',
    question: 'Which of the following best describes "business email compromise"?',
    optionA: 'Multi-Factor Authentication (MFA) requires two or more independent proofs of identity to log in — typically something you know (password), something you have (a phone/token), or something you are (biometrics). It dramatically reduces the impact of a stolen password. Two-Factor Authentication (2FA) is the common two-factor case of MFA.',
    optionB: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    optionC: 'Patch management is the process of regularly applying vendor updates that fix known vulnerabilities, closing the window of exposure between a flaw being disclosed and it being exploited.',
    optionD: 'Business Email Compromise is a targeted scam where an attacker impersonates or compromises an executive or vendor email account to trick an employee into making a fraudulent wire transfer or disclosing sensitive data.',
    correctOption: 'D',
    topic: 'business email compromise',
    moduleTag: 'Social Engineering',
    topicTag: 'Business Email Compromise',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Business Email Compromise is a targeted scam where an attacker impersonates or compromises an executive or vendor email account to trick an employee into making a fraudulent wire transfer or disclosing sensitive data.',
    isActive: true,
  },
  {
    questionId: 'def-3',
    question: 'Which of the following best describes "cross-site request forgery"?',
    optionA: 'A trojan is malware disguised as legitimate software; unlike a worm it does not self-replicate — it relies on tricking a user into installing or running it.',
    optionB: 'A threat actor is any individual or group that carries out (or could carry out) a malicious attack — ranging from lone hackers and criminal organizations to insider threats and nation-state groups.',
    optionC: 'Public Key Infrastructure (PKI) is the system of certificate authorities, digital certificates, and public/private key pairs used to verify identities and enable encrypted, trusted communication (e.g. HTTPS).',
    optionD: 'Cross-Site Request Forgery (CSRF) tricks a logged-in user\'s browser into submitting an unwanted request to a site where they\'re authenticated, performing an action (like changing account settings) without their consent. Prevented with anti-CSRF tokens and SameSite cookies.',
    correctOption: 'D',
    topic: 'cross-site request forgery',
    moduleTag: 'Web Security',
    topicTag: 'Cross-Site Request Forgery',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'Cross-Site Request Forgery (CSRF) tricks a logged-in user\'s browser into submitting an unwanted request to a site where they\'re authenticated, performing an action (like changing account settings) without their consent. Prevented with anti-CSRF tokens and SameSite cookies.',
    isActive: true,
  },
  {
    questionId: 'def-4',
    question: 'Which of the following best describes "brute force"?',
    optionA: 'A Denial-of-Service (DoS) attack floods a system with traffic or requests to exhaust its resources and make it unavailable to legitimate users. A Distributed Denial-of-Service (DDoS) attack does this from many compromised machines (a botnet) at once, making it much harder to block.',
    optionB: 'A honeypot is a decoy system deliberately exposed to attract attackers, letting defenders study attack techniques and detect intrusions without risking real assets.',
    optionC: 'A Man-in-the-Middle (MITM) attack intercepts communication between two parties who believe they are talking directly to each other, letting the attacker eavesdrop on or alter the traffic. Mitigated with TLS encryption, certificate validation, and certificate pinning.',
    optionD: 'A brute-force attack systematically tries many password or key combinations until the correct one is found. It is mitigated with account lockouts, rate limiting, strong password policies, and multi-factor authentication.',
    correctOption: 'D',
    topic: 'brute force',
    moduleTag: 'System Security',
    topicTag: 'Brute Force',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'A brute-force attack systematically tries many password or key combinations until the correct one is found. It is mitigated with account lockouts, rate limiting, strong password policies, and multi-factor authentication.',
    isActive: true,
  },
  {
    questionId: 'def-5',
    question: 'Which of the following best describes "session hijacking"?',
    optionA: 'Session hijacking is when an attacker steals or predicts a valid session token (e.g. a cookie) to impersonate a logged-in user without needing their password. Mitigated with secure/HttpOnly cookies, TLS everywhere, and session regeneration on login.',
    optionB: 'Zero Trust is a security model that assumes no user or device should be trusted by default, even inside the network perimeter — every request is authenticated, authorized, and encrypted based on identity and context, not network location.',
    optionC: 'Malware is any software intentionally designed to cause harm to a system or its users — including viruses, worms, trojans, ransomware, and spyware. Defended against with endpoint protection (antivirus/EDR), patching, and least-privilege access.',
    optionD: 'A rootkit is malware designed to hide its own presence and maintain privileged (root/admin) access on a compromised system, often by tampering with the operating system itself, making it very hard to detect with normal tools.',
    correctOption: 'A',
    topic: 'session hijacking',
    moduleTag: 'System Security',
    topicTag: 'Session Hijacking',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'Session hijacking is when an attacker steals or predicts a valid session token (e.g. a cookie) to impersonate a logged-in user without needing their password. Mitigated with secure/HttpOnly cookies, TLS everywhere, and session regeneration on login.',
    isActive: true,
  },
  {
    questionId: 'def-6',
    question: 'Which of the following best describes "ransomware"?',
    optionA: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    optionB: 'Public Key Infrastructure (PKI) is the system of certificate authorities, digital certificates, and public/private key pairs used to verify identities and enable encrypted, trusted communication (e.g. HTTPS).',
    optionC: 'A watering-hole attack compromises a website the target audience is known to visit, so that visiting it silently infects them — instead of attacking the target directly.',
    optionD: 'Ransomware is malware that encrypts a victim\'s files (or locks the system) and demands payment for the decryption key. Defended against with offline/immutable backups, endpoint protection, patching, and user training against the phishing emails that usually deliver it.',
    correctOption: 'D',
    topic: 'ransomware',
    moduleTag: 'System Security',
    topicTag: 'Ransomware',
    difficulty: 'Easy',
    testForm: 'POST_B',
    explanation: 'Ransomware is malware that encrypts a victim\'s files (or locks the system) and demands payment for the decryption key. Defended against with offline/immutable backups, endpoint protection, patching, and user training against the phishing emails that usually deliver it.',
    isActive: true,
  },
  {
    questionId: 'def-7',
    question: 'Which of the following best describes "social engineering"?',
    optionA: 'Business Email Compromise is a targeted scam where an attacker impersonates or compromises an executive or vendor email account to trick an employee into making a fraudulent wire transfer or disclosing sensitive data.',
    optionB: 'SQL Injection is an attack where untrusted input is inserted into a database query without proper sanitization, letting an attacker read, modify, or delete data they should not have access to. It is prevented with parameterized queries/prepared statements and strict input validation.',
    optionC: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    optionD: 'Social engineering is manipulating people, rather than systems, into breaking normal security procedures — e.g. tricking someone into revealing a password or letting an unauthorized person into a building. Phishing, pretexting, and baiting are all forms of it. Mitigated primarily with security-awareness training.',
    correctOption: 'D',
    topic: 'social engineering',
    moduleTag: 'Social Engineering',
    topicTag: 'Social Engineering',
    difficulty: 'Easy',
    testForm: 'PRE_A',
    explanation: 'Social engineering is manipulating people, rather than systems, into breaking normal security procedures — e.g. tricking someone into revealing a password or letting an unauthorized person into a building. Phishing, pretexting, and baiting are all forms of it. Mitigated primarily with security-awareness training.',
    isActive: true,
  },
  {
    questionId: 'def-8',
    question: 'Which of the following best describes "insider threat"?',
    optionA: 'Digital forensics is the practice of collecting, preserving, and analyzing digital evidence after a security incident to determine what happened, how, and by whom, often for legal or remediation purposes.',
    optionB: 'A supply chain attack compromises a trusted third-party component, vendor, or software update mechanism to reach the ultimate target indirectly — e.g. inserting malicious code into a library that thousands of applications depend on.',
    optionC: 'An insider threat is a security risk that originates from someone with legitimate access — an employee, contractor, or partner — who misuses that access, whether maliciously or through negligence. Mitigated with least privilege, activity monitoring, and offboarding processes.',
    optionD: 'A Web Application Firewall (WAF) filters and monitors HTTP traffic to and from a web application specifically, blocking common attack patterns like SQL injection and XSS payloads at the application layer.',
    correctOption: 'C',
    topic: 'insider threat',
    moduleTag: 'System Security',
    topicTag: 'Insider Threat',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'An insider threat is a security risk that originates from someone with legitimate access — an employee, contractor, or partner — who misuses that access, whether maliciously or through negligence. Mitigated with least privilege, activity monitoring, and offboarding processes.',
    isActive: true,
  },
  {
    questionId: 'def-9',
    question: 'Which of the following best describes "keylogger"?',
    optionA: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    optionB: 'A keylogger is malware or hardware that secretly records keystrokes to capture passwords, messages, and other sensitive input typed by the victim.',
    optionC: 'Cross-Site Request Forgery (CSRF) tricks a logged-in user\'s browser into submitting an unwanted request to a site where they\'re authenticated, performing an action (like changing account settings) without their consent. Prevented with anti-CSRF tokens and SameSite cookies.',
    optionD: 'A rootkit is malware designed to hide its own presence and maintain privileged (root/admin) access on a compromised system, often by tampering with the operating system itself, making it very hard to detect with normal tools.',
    correctOption: 'B',
    topic: 'keylogger',
    moduleTag: 'System Security',
    topicTag: 'Keylogger',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'A keylogger is malware or hardware that secretly records keystrokes to capture passwords, messages, and other sensitive input typed by the victim.',
    isActive: true,
  },
  {
    questionId: 'def-10',
    question: 'Which of the following best describes "trojan"?',
    optionA: 'Cross-Site Scripting (XSS) is an attack where malicious script is injected into a web page viewed by other users, letting the attacker run code in their browsers to steal session cookies, deface content, or redirect them. Prevented with output encoding, input sanitization, and a Content Security Policy.',
    optionB: 'A watering-hole attack compromises a website the target audience is known to visit, so that visiting it silently infects them — instead of attacking the target directly.',
    optionC: 'Data Loss Prevention (DLP) is a set of tools and policies that detect and block sensitive data (like credit card numbers or confidential documents) from leaving an organization through channels like email or USB drives.',
    optionD: 'A trojan is malware disguised as legitimate software; unlike a worm it does not self-replicate — it relies on tricking a user into installing or running it.',
    correctOption: 'D',
    topic: 'trojan',
    moduleTag: 'System Security',
    topicTag: 'Trojan',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'A trojan is malware disguised as legitimate software; unlike a worm it does not self-replicate — it relies on tricking a user into installing or running it.',
    isActive: true,
  },
  {
    questionId: 'def-11',
    question: 'Which of the following best describes "botnet"?',
    optionA: 'A zero-day is a software vulnerability that is unknown to the vendor (and therefore has no patch yet) at the time it is discovered or exploited. Zero-day exploits are especially dangerous because standard signature-based defenses have nothing to detect. Mitigated with defense-in-depth, network segmentation, and behavior-based detection rather than relying on patches alone.',
    optionB: 'A botnet is a network of compromised devices ("bots") controlled remotely by an attacker, typically used to launch DDoS attacks, send spam, or mine cryptocurrency at scale.',
    optionC: 'Social engineering is manipulating people, rather than systems, into breaking normal security procedures — e.g. tricking someone into revealing a password or letting an unauthorized person into a building. Phishing, pretexting, and baiting are all forms of it. Mitigated primarily with security-awareness training.',
    optionD: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    correctOption: 'B',
    topic: 'botnet',
    moduleTag: 'Network Security',
    topicTag: 'Botnet',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'A botnet is a network of compromised devices ("bots") controlled remotely by an attacker, typically used to launch DDoS attacks, send spam, or mine cryptocurrency at scale.',
    isActive: true,
  },
  {
    questionId: 'def-12',
    question: 'Which of the following best describes "typosquatting"?',
    optionA: 'Typosquatting registers domain names that are common misspellings of a legitimate site (e.g. "gooogle.com") to catch users who mistype a URL, often for phishing or serving malware.',
    optionB: 'A SIEM (Security Information and Event Management) system aggregates and correlates log data from across an organization to detect suspicious patterns and support incident investigation.',
    optionC: 'A brute-force attack systematically tries many password or key combinations until the correct one is found. It is mitigated with account lockouts, rate limiting, strong password policies, and multi-factor authentication.',
    optionD: 'Social engineering is manipulating people, rather than systems, into breaking normal security procedures — e.g. tricking someone into revealing a password or letting an unauthorized person into a building. Phishing, pretexting, and baiting are all forms of it. Mitigated primarily with security-awareness training.',
    correctOption: 'A',
    topic: 'typosquatting',
    moduleTag: 'Social Engineering',
    topicTag: 'Typosquatting',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Typosquatting registers domain names that are common misspellings of a legitimate site (e.g. "gooogle.com") to catch users who mistype a URL, often for phishing or serving malware.',
    isActive: true,
  },
  {
    questionId: 'def-13',
    question: 'Which of the following best describes "intrusion prevention system"?',
    optionA: 'Business Email Compromise is a targeted scam where an attacker impersonates or compromises an executive or vendor email account to trick an employee into making a fraudulent wire transfer or disclosing sensitive data.',
    optionB: 'A Man-in-the-Middle (MITM) attack intercepts communication between two parties who believe they are talking directly to each other, letting the attacker eavesdrop on or alter the traffic. Mitigated with TLS encryption, certificate validation, and certificate pinning.',
    optionC: 'A Web Application Firewall (WAF) filters and monitors HTTP traffic to and from a web application specifically, blocking common attack patterns like SQL injection and XSS payloads at the application layer.',
    optionD: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    correctOption: 'D',
    topic: 'intrusion prevention system',
    moduleTag: 'Network Security',
    topicTag: 'Intrusion Prevention System',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    isActive: true,
  },
  {
    questionId: 'def-14',
    question: 'Which of the following best describes "encryption"?',
    optionA: 'Encryption transforms data into unreadable ciphertext using a key, so only someone with the correct key can decrypt it back to plaintext. Symmetric encryption uses the same key to encrypt and decrypt (fast, used for bulk data); asymmetric encryption uses a public/private key pair (used for secure key exchange and digital signatures).',
    optionB: 'A Web Application Firewall (WAF) filters and monitors HTTP traffic to and from a web application specifically, blocking common attack patterns like SQL injection and XSS payloads at the application layer.',
    optionC: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    optionD: 'SQL Injection is an attack where untrusted input is inserted into a database query without proper sanitization, letting an attacker read, modify, or delete data they should not have access to. It is prevented with parameterized queries/prepared statements and strict input validation.',
    correctOption: 'A',
    topic: 'encryption',
    moduleTag: 'Cryptography',
    topicTag: 'Encryption',
    difficulty: 'Easy',
    testForm: 'POST_B',
    explanation: 'Encryption transforms data into unreadable ciphertext using a key, so only someone with the correct key can decrypt it back to plaintext. Symmetric encryption uses the same key to encrypt and decrypt (fast, used for bulk data); asymmetric encryption uses a public/private key pair (used for secure key exchange and digital signatures).',
    isActive: true,
  },
  {
    questionId: 'def-15',
    question: 'Which of the following best describes "web application firewall"?',
    optionA: 'A Web Application Firewall (WAF) filters and monitors HTTP traffic to and from a web application specifically, blocking common attack patterns like SQL injection and XSS payloads at the application layer.',
    optionB: 'A rootkit is malware designed to hide its own presence and maintain privileged (root/admin) access on a compromised system, often by tampering with the operating system itself, making it very hard to detect with normal tools.',
    optionC: 'A vulnerability is a weakness in a system — a bug, misconfiguration, or design flaw — that could be exploited to cause harm. A vulnerability only becomes dangerous once an exploit is developed and used against it.',
    optionD: 'The CIA Triad is the foundational model of information security: Confidentiality (only authorized parties can access data), Integrity (data cannot be altered undetected), and Availability (systems and data are accessible when needed). Most security controls map to protecting one or more of these three properties.',
    correctOption: 'A',
    topic: 'web application firewall',
    moduleTag: 'Web Security',
    topicTag: 'Web Application Firewall',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'A Web Application Firewall (WAF) filters and monitors HTTP traffic to and from a web application specifically, blocking common attack patterns like SQL injection and XSS payloads at the application layer.',
    isActive: true,
  },
  {
    questionId: 'def-16',
    question: 'Which of the following best describes "rate limiting"?',
    optionA: 'Rate limiting restricts how many requests a client can make in a given time window, mitigating brute-force login attempts, credential stuffing, and denial-of-service traffic.',
    optionB: 'A brute-force attack systematically tries many password or key combinations until the correct one is found. It is mitigated with account lockouts, rate limiting, strong password policies, and multi-factor authentication.',
    optionC: 'A firewall is a network security control that monitors and filters incoming and outgoing traffic based on defined rules, blocking traffic that does not meet the allowed criteria. It is a perimeter defense, not a substitute for securing the applications behind it.',
    optionD: 'Multi-Factor Authentication (MFA) requires two or more independent proofs of identity to log in — typically something you know (password), something you have (a phone/token), or something you are (biometrics). It dramatically reduces the impact of a stolen password. Two-Factor Authentication (2FA) is the common two-factor case of MFA.',
    correctOption: 'A',
    topic: 'rate limiting',
    moduleTag: 'Web Security',
    topicTag: 'Rate Limiting',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Rate limiting restricts how many requests a client can make in a given time window, mitigating brute-force login attempts, credential stuffing, and denial-of-service traffic.',
    isActive: true,
  },
  {
    questionId: 'def-17',
    question: 'Which of the following best describes "zero trust"?',
    optionA: 'Spear phishing is a targeted form of phishing aimed at a specific person or organization, using researched personal details (name, role, colleagues) to make the message far more convincing than a generic phishing blast.',
    optionB: 'Endpoint Detection and Response (EDR) continuously monitors endpoint devices (laptops, servers) for suspicious behavior, enabling detection and rapid response to threats that bypass traditional antivirus.',
    optionC: 'The Principle of Least Privilege states that a user, process, or system should only be granted the minimum access necessary to perform its function — limiting the damage possible if that account or process is compromised.',
    optionD: 'Zero Trust is a security model that assumes no user or device should be trusted by default, even inside the network perimeter — every request is authenticated, authorized, and encrypted based on identity and context, not network location.',
    correctOption: 'D',
    topic: 'zero trust',
    moduleTag: 'Network Security',
    topicTag: 'Zero Trust',
    difficulty: 'Hard',
    testForm: 'PRE_A',
    explanation: 'Zero Trust is a security model that assumes no user or device should be trusted by default, even inside the network perimeter — every request is authenticated, authorized, and encrypted based on identity and context, not network location.',
    isActive: true,
  },
  {
    questionId: 'def-18',
    question: 'Which of the following best describes "network segmentation"?',
    optionA: 'Network segmentation divides a network into isolated zones so that a compromise in one segment cannot easily spread to others, limiting the blast radius of an attack.',
    optionB: 'A VPN (Virtual Private Network) creates an encrypted tunnel for network traffic between a device and a remote server, hiding the traffic from anyone on the intermediate network and often masking the origin IP address.',
    optionC: 'Credential stuffing uses username/password pairs leaked from one breach to automatically try logging into other, unrelated services — it works because people reuse passwords. Mitigated with unique passwords per site, MFA, and login-anomaly detection.',
    optionD: 'An Intrusion Detection System (IDS) monitors network or system activity for suspicious behavior and alerts defenders, but does not block traffic itself — that is the job of an IPS.',
    correctOption: 'A',
    topic: 'network segmentation',
    moduleTag: 'Network Security',
    topicTag: 'Network Segmentation',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Network segmentation divides a network into isolated zones so that a compromise in one segment cannot easily spread to others, limiting the blast radius of an attack.',
    isActive: true,
  },
  {
    questionId: 'def-19',
    question: 'Which of the following best describes "security awareness training"?',
    optionA: 'Rate limiting restricts how many requests a client can make in a given time window, mitigating brute-force login attempts, credential stuffing, and denial-of-service traffic.',
    optionB: 'Security awareness training teaches employees to recognize and respond correctly to threats like phishing and social engineering — the human counterpart to technical controls, since people are frequently the weakest link.',
    optionC: 'Digital forensics is the practice of collecting, preserving, and analyzing digital evidence after a security incident to determine what happened, how, and by whom, often for legal or remediation purposes.',
    optionD: 'Defense in depth is a strategy of layering multiple, independent security controls (network, host, application, human) so that if one layer fails or is bypassed, others still provide protection — no single point of failure.',
    correctOption: 'B',
    topic: 'security awareness training',
    moduleTag: 'Social Engineering',
    topicTag: 'Security Awareness Training',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'Security awareness training teaches employees to recognize and respond correctly to threats like phishing and social engineering — the human counterpart to technical controls, since people are frequently the weakest link.',
    isActive: true,
  },
  {
    questionId: 'def-20',
    question: 'Which of the following best describes "vulnerability scanning"?',
    optionA: 'Vulnerability scanning uses automated tools to check systems and software against databases of known vulnerabilities, giving a broad but shallower picture than manual penetration testing.',
    optionB: 'A vulnerability is a weakness in a system — a bug, misconfiguration, or design flaw — that could be exploited to cause harm. A vulnerability only becomes dangerous once an exploit is developed and used against it.',
    optionC: 'Session hijacking is when an attacker steals or predicts a valid session token (e.g. a cookie) to impersonate a logged-in user without needing their password. Mitigated with secure/HttpOnly cookies, TLS everywhere, and session regeneration on login.',
    optionD: 'A Man-in-the-Middle (MITM) attack intercepts communication between two parties who believe they are talking directly to each other, letting the attacker eavesdrop on or alter the traffic. Mitigated with TLS encryption, certificate validation, and certificate pinning.',
    correctOption: 'A',
    topic: 'vulnerability scanning',
    moduleTag: 'System Security',
    topicTag: 'Vulnerability Scanning',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Vulnerability scanning uses automated tools to check systems and software against databases of known vulnerabilities, giving a broad but shallower picture than manual penetration testing.',
    isActive: true,
  },
  {
    questionId: 'def-21',
    question: 'Which of the following best describes "sandbox"?',
    optionA: 'The Principle of Least Privilege states that a user, process, or system should only be granted the minimum access necessary to perform its function — limiting the damage possible if that account or process is compromised.',
    optionB: 'Phishing is a social-engineering attack where an attacker sends fraudulent messages (usually email) that impersonate a trusted sender to trick the recipient into revealing credentials, clicking a malicious link, or downloading malware. It relies on deception rather than technical exploitation.',
    optionC: 'An Advanced Persistent Threat (APT) is a well-resourced, often state-sponsored attacker that gains long-term, stealthy access to a network to steal data over an extended period, rather than causing immediate, obvious damage.',
    optionD: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    correctOption: 'D',
    topic: 'sandbox',
    moduleTag: 'System Security',
    topicTag: 'Sandbox',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    isActive: true,
  },
  {
    questionId: 'def-22',
    question: 'Which of the following best describes "red team"?',
    optionA: 'An Intrusion Prevention System (IPS) monitors traffic like an IDS but can actively block or drop malicious traffic in real time rather than only alerting.',
    optionB: 'A keylogger is malware or hardware that secretly records keystrokes to capture passwords, messages, and other sensitive input typed by the victim.',
    optionC: 'A red team simulates real attackers to test an organization\'s defenses (offensive security). A blue team is the defenders who detect and respond to those simulated (or real) attacks. Exercises combining both are called purple team exercises.',
    optionD: 'Defense in depth is a strategy of layering multiple, independent security controls (network, host, application, human) so that if one layer fails or is bypassed, others still provide protection — no single point of failure.',
    correctOption: 'C',
    topic: 'red team',
    moduleTag: 'System Security',
    topicTag: 'Red Team',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'A red team simulates real attackers to test an organization\'s defenses (offensive security). A blue team is the defenders who detect and respond to those simulated (or real) attacks. Exercises combining both are called purple team exercises.',
    isActive: true,
  },
  {
    questionId: 'def-23',
    question: 'Which of the following best describes "threat actor"?',
    optionA: 'A Denial-of-Service (DoS) attack floods a system with traffic or requests to exhaust its resources and make it unavailable to legitimate users. A Distributed Denial-of-Service (DDoS) attack does this from many compromised machines (a botnet) at once, making it much harder to block.',
    optionB: 'The attack surface is the sum of all the points where an unauthorized user could try to enter or extract data from a system — every exposed endpoint, open port, input field, and third-party integration. Reducing it (fewer exposed services, less code, fewer permissions) is a core defensive strategy.',
    optionC: 'A brute-force attack systematically tries many password or key combinations until the correct one is found. It is mitigated with account lockouts, rate limiting, strong password policies, and multi-factor authentication.',
    optionD: 'A threat actor is any individual or group that carries out (or could carry out) a malicious attack — ranging from lone hackers and criminal organizations to insider threats and nation-state groups.',
    correctOption: 'D',
    topic: 'threat actor',
    moduleTag: 'System Security',
    topicTag: 'Threat Actor',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'A threat actor is any individual or group that carries out (or could carry out) a malicious attack — ranging from lone hackers and criminal organizations to insider threats and nation-state groups.',
    isActive: true,
  },
  {
    questionId: 'def-24',
    question: 'Which of the following best describes "exploit"?',
    optionA: 'Session hijacking is when an attacker steals or predicts a valid session token (e.g. a cookie) to impersonate a logged-in user without needing their password. Mitigated with secure/HttpOnly cookies, TLS everywhere, and session regeneration on login.',
    optionB: 'Sandboxing runs untrusted code or files in an isolated environment separate from the production system, so that if the code is malicious it cannot affect real systems or data.',
    optionC: 'An exploit is a piece of code or technique that takes advantage of a specific vulnerability to cause unintended behavior, such as gaining unauthorized access or executing arbitrary code.',
    optionD: 'Credential stuffing uses username/password pairs leaked from one breach to automatically try logging into other, unrelated services — it works because people reuse passwords. Mitigated with unique passwords per site, MFA, and login-anomaly detection.',
    correctOption: 'C',
    topic: 'exploit',
    moduleTag: 'System Security',
    topicTag: 'Exploit',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'An exploit is a piece of code or technique that takes advantage of a specific vulnerability to cause unintended behavior, such as gaining unauthorized access or executing arbitrary code.',
    isActive: true,
  },
  {
    questionId: 'def-25',
    question: 'Which of the following best describes "digital forensics"?',
    optionA: 'A zero-day is a software vulnerability that is unknown to the vendor (and therefore has no patch yet) at the time it is discovered or exploited. Zero-day exploits are especially dangerous because standard signature-based defenses have nothing to detect. Mitigated with defense-in-depth, network segmentation, and behavior-based detection rather than relying on patches alone.',
    optionB: 'A botnet is a network of compromised devices ("bots") controlled remotely by an attacker, typically used to launch DDoS attacks, send spam, or mine cryptocurrency at scale.',
    optionC: 'Phishing is a social-engineering attack where an attacker sends fraudulent messages (usually email) that impersonate a trusted sender to trick the recipient into revealing credentials, clicking a malicious link, or downloading malware. It relies on deception rather than technical exploitation.',
    optionD: 'Digital forensics is the practice of collecting, preserving, and analyzing digital evidence after a security incident to determine what happened, how, and by whom, often for legal or remediation purposes.',
    correctOption: 'D',
    topic: 'digital forensics',
    moduleTag: 'System Security',
    topicTag: 'Digital Forensics',
    difficulty: 'Hard',
    testForm: 'PRE_A',
    explanation: 'Digital forensics is the practice of collecting, preserving, and analyzing digital evidence after a security incident to determine what happened, how, and by whom, often for legal or remediation purposes.',
    isActive: true,
  },
];
