// Hand-authored "Apply"-level questions, each grounded in a real seeded
// scenario/attack/defense pairing from scenarioData.ts / explicitRules.ts
// (not invented in isolation) — verified against the live database, not
// just plausible-sounding.
import type { QuizQuestionSeed } from './quizQuestionTypes';

export const APPLICATION_QUESTIONS: QuizQuestionSeed[] = [
  {
    questionId: 'app-1',
    question: "In the \"HR Onboarding Team\" scenario, an employee receives an urgent email that appears to come from the CEO asking for confidential payroll data. What is the most appropriate action?",
    optionA: 'Reply immediately because the sender appears to be senior',
    optionB: 'Verify the request through a known phone number or another trusted channel',
    optionC: 'Forward it to all employees for visibility',
    optionD: 'Disable the email account permanently',
    correctOption: 'B',
    topic: 'Spear Phishing',
    moduleTag: 'Social Engineering',
    topicTag: 'Spear Phishing',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: "Spear phishing relies on urgency and apparent authority to bypass judgment. Verifying through a separate, already-trusted channel (a known phone number, not one supplied in the email) confirms the request without giving the attacker what they asked for — this is exactly the countermeasure that defeats Spear Phishing in the HR Onboarding Team scenario (Security Awareness Training).",
    isActive: true,
  },
  {
    questionId: 'app-2',
    question: "The \"Online Banking Portal\" scenario's login form builds SQL queries by directly concatenating user input. Which control most directly prevents SQL Injection here?",
    optionA: 'Anti-CSRF tokens',
    optionB: 'Parameterized queries',
    optionC: 'Password rotation policy',
    optionD: 'TLS certificates',
    correctOption: 'B',
    topic: 'SQL Injection',
    moduleTag: 'Web Security',
    topicTag: 'SQL Injection',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Parameterized queries separate SQL code from user-supplied data, so injected SQL is treated as a literal value rather than executable syntax. Anti-CSRF tokens check request origin, not query safety, and TLS/password rotation address entirely different threats — neither stops injected SQL.',
    isActive: true,
  },
  {
    questionId: 'app-3',
    question: "In the \"Online Banking Portal\" scenario, a defender enables Object-Level Authorization against a CSRF (forged fund-transfer request) attack. What is the most accurate outcome?",
    optionA: 'Defended — the forged request is rejected outright',
    optionB: 'Partially defended — ownership checks limit the damage but do not stop the forged request itself',
    optionC: 'Breached — authorization checks are irrelevant to CSRF',
    optionD: 'Breached — object-level authorization only protects attackers, not victims',
    correctOption: 'B',
    topic: 'Cross-Site Request Forgery (CSRF)',
    moduleTag: 'Web Security',
    topicTag: 'CSRF',
    difficulty: 'Hard',
    testForm: 'PRE_A',
    explanation: "Object-Level Authorization doesn't stop a forged request from being processed — it still executes — but it does confirm the forged request can only touch resources the victim actually owns, which limits (without preventing) the blast radius. That's genuine partial credit, not a full defense or a full breach.",
    isActive: true,
  },
  {
    questionId: 'app-4',
    question: "At the \"Internet Exchange Point\" scenario, an attacker announces false BGP routes to redirect internet traffic. Which control most directly stops this?",
    optionA: 'Deep Packet Inspection',
    optionB: 'RPKI Route Validation',
    optionC: 'Frequency Hopping Spread Spectrum',
    optionD: 'SYN Cookies',
    correctOption: 'B',
    topic: 'BGP Hijacking',
    moduleTag: 'Network Security',
    topicTag: 'BGP Hijacking',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'RPKI cryptographically ties a route announcement to the network that legitimately owns the address block, so a forged BGP announcement fails validation. Deep Packet Inspection checks packet structure, not route ownership, so a well-formed forged route passes right through it.',
    isActive: true,
  },
  {
    questionId: 'app-5',
    question: "A defender at the \"Internet Exchange Point\" scenario chooses RPKI Route Validation against an incoming Signal Jamming attack. What happens?",
    optionA: 'Defended — RPKI stops all Network Security attacks',
    optionB: 'Partially defended — some protection carries over',
    optionC: 'Breached — RPKI validates routing announcements, not radio-layer jamming',
    optionD: 'Breached — RPKI only functions on wireless networks',
    correctOption: 'C',
    topic: 'Signal Jamming',
    moduleTag: 'Network Security',
    topicTag: 'Signal Jamming',
    difficulty: 'Hard',
    testForm: 'PRE_A',
    explanation: 'RPKI is a routing-security mechanism operating on BGP announcements; it has no visibility into or effect on the physical radio spectrum, so it provides zero protection against RF jamming — sharing a module ("Network Security") does not mean two controls are interchangeable.',
    isActive: true,
  },
  {
    questionId: 'app-6',
    question: "In the \"Healthcare Database\" scenario, ransomware encrypts patient records. Which control allows recovery without paying the ransom?",
    optionA: 'Multi-Factor Authentication',
    optionB: 'Offline, immutable backups',
    optionC: 'Firewall rules',
    optionD: 'Code obfuscation',
    correctOption: 'B',
    topic: 'Ransomware',
    moduleTag: 'System Security',
    topicTag: 'Ransomware',
    difficulty: 'Easy',
    testForm: 'POST_B',
    explanation: 'Offline, immutable backups cannot be reached or altered by ransomware running on the production system, so records can be restored without paying. MFA and firewalls are preventive controls for other attack paths — once ransomware has already encrypted the data, they don\'t help recover it.',
    isActive: true,
  },
  {
    questionId: 'app-7',
    question: "Also in the \"Healthcare Database\" scenario, an attacker who compromised a low-privilege support account attempts privilege escalation to gain admin rights. Which control most directly limits this?",
    optionA: 'Least privilege / role-based access control',
    optionB: 'Rate limiting',
    optionC: 'TLS encryption',
    optionD: 'DNSSEC',
    correctOption: 'A',
    topic: 'Privilege Escalation',
    moduleTag: 'System Security',
    topicTag: 'Privilege Escalation',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: 'Least privilege / RBAC limits every account, including a compromised one, to the minimum permissions it actually needs — so even a successfully compromised support account has nowhere higher to escalate to. Rate limiting, TLS, and DNSSEC address unrelated threats (brute force, eavesdropping, DNS spoofing).',
    isActive: true,
  },
  {
    questionId: 'app-8',
    question: "In the \"Personal Password Manager\" scenario, passwords are stored using unsalted, fast hashes and get cracked quickly offline. Which control most directly fixes this weakness?",
    optionA: 'Salted, slow hashing such as bcrypt or Argon2',
    optionB: 'TLS everywhere',
    optionC: 'Rate limiting login attempts',
    optionD: 'Frequency hopping',
    correctOption: 'A',
    topic: 'Weak Password Hashing',
    moduleTag: 'Cryptography',
    topicTag: 'Password Hashing',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Salted, slow hashing algorithms (bcrypt/Argon2) make each guess computationally expensive and defeat precomputed lookup tables, directly countering offline cracking. TLS protects data in transit, not how it\'s stored at rest, so it does nothing for an already-stolen password database.',
    isActive: true,
  },
  {
    questionId: 'app-9',
    question: "In the \"Corporate VPN Tunnel\" scenario, an attacker captures a valid encrypted authentication message and resends it later to gain access again. Which control most directly stops this?",
    optionA: 'Timestamp and nonce validation',
    optionB: 'Longer encryption keys',
    optionC: 'A stronger firewall rule',
    optionD: 'Employee security awareness training',
    correctOption: 'A',
    topic: 'Replay Attack',
    moduleTag: 'Cryptography',
    topicTag: 'Replay Attack',
    difficulty: 'Hard',
    testForm: 'PRE_A',
    explanation: 'A replayed message is already validly encrypted — the problem is that it\'s being resent, not that it\'s weakly encrypted. Timestamp and nonce validation rejects messages that are stale or have already been used once, which is exactly what a replay attack depends on.',
    isActive: true,
  },
  {
    questionId: 'app-10',
    question: "In the \"Fortune 500 Executive Office\" scenario, a forged executive email pressures an employee into an urgent wire transfer. Which control most directly limits the damage from this kind of attack, even if the forged email itself isn't caught?",
    optionA: 'Antivirus software',
    optionB: 'Multi-person financial approval workflows',
    optionC: 'Stronger Wi-Fi encryption',
    optionD: 'Patch management',
    correctOption: 'B',
    topic: 'Business Email Compromise',
    moduleTag: 'Social Engineering',
    topicTag: 'Business Email Compromise',
    difficulty: 'Medium',
    testForm: 'POST_B',
    explanation: 'Business Email Compromise targets a human decision, not a technical vulnerability, so technical controls like antivirus or patching don\'t apply. Requiring multi-person sign-off on financial transfers adds a check that survives even a convincing forged email, since no single deceived employee can complete the transfer alone.',
    isActive: true,
  },
  {
    questionId: 'app-11',
    question: "In the \"Online Banking Portal\" scenario, changing the numeric id in a transaction-history URL lets a user view another customer's transactions. Which control most directly prevents this?",
    optionA: 'Anti-CSRF tokens',
    optionB: 'Verifying record ownership on every resource access',
    optionC: 'Password complexity rules',
    optionD: 'DNSSEC',
    correctOption: 'B',
    topic: 'Insecure Direct Object Reference (IDOR)',
    moduleTag: 'Web Security',
    topicTag: 'IDOR',
    difficulty: 'Medium',
    testForm: 'PRE_A',
    explanation: "IDOR happens when an application trusts a client-supplied id without checking who it belongs to. Verifying ownership on every access closes exactly that gap; anti-CSRF tokens address forged requests, not id-based access checks, so they don't help here.",
    isActive: true,
  },
  {
    questionId: 'app-12',
    question: "The \"Government Network\" scenario experiences a sudden flood of traffic from thousands of sources designed to exhaust server resources. Which control most directly mitigates this?",
    optionA: 'DDoS mitigation and traffic scrubbing',
    optionB: 'Parameterized queries',
    optionC: 'Object-level authorization',
    optionD: 'Digital forensics',
    correctOption: 'A',
    topic: 'DDoS',
    moduleTag: 'Network Security',
    topicTag: 'DDoS',
    difficulty: 'Easy',
    testForm: 'POST_B',
    explanation: 'DDoS mitigation and traffic scrubbing absorb and filter malicious traffic upstream before it can exhaust the target\'s resources. Parameterized queries and object-level authorization are application-layer controls for entirely different attack types and have no effect on volumetric network flooding.',
    isActive: true,
  },
];
